name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # mainブランチに保存されたら実行

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x # 使用しているバージョンに合わせる

      - name: Publish .NET Project
        run: dotnet publish BrothersEnglishApp.csproj -c Release -o release --nologo

      # GitHub Pages用の404対策（index.htmlをコピーするおまじない）
      - name: Change base-tag and copy index.html to 404.html
        run: |
          sed -i 's/<base href="\/" \/>/<base href="\/BrothersEnglishApp\/" \/>/g' release/wwwroot/index.html
          cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit and Push to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages # 公開専用のブランチに送る
